# Generated by Django 4.1.4 on 2023-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fowlrun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fowlrunconditions',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fowlrunconditions',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
