# Generated by Django 4.1.4 on 2023-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fowlrun', '0002_alter_fowlrunconditions_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fowlrunconditions',
            name='humidity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fowlrunconditions',
            name='temperature',
            field=models.IntegerField(default=1),
        ),
    ]
